# SPDX-License-Identifier: LicenseRef-OmniCompass-Evaluation-1.0
# Copyright (c) 2026 The Omni-Compass LLC. All rights reserved.
# Evaluation and simulation use only; any commercialization, monetization or other use requires a signed, paid
# Omni-Compass Enterprise License. See LICENSE, NOTICE and DISCLOSURES.md.
# All patents, copyrights and trademarks filed in the USA. www.omni-compass.com
# The one permission the add-on test adds to Omni-Compass's least-privilege identity (deploy/kind/rbac-omni.yaml): KEDA
# owns php-apache's HPA and rebuilds it from its ScaledObject, so the plug (scripts/kubectl_keda.py) carries the HPA moves
# to that one ScaledObject. Named object only; no create, no delete, nothing in KEDA's own namespace.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: {name: omni-compass-keda, namespace: default}
rules:
  - apiGroups: ["keda.sh"]
    resources: ["scaledobjects"]
    resourceNames: ["php-apache"]
    verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: {name: omni-compass-keda, namespace: default}
roleRef: {apiGroup: rbac.authorization.k8s.io, kind: Role, name: omni-compass-keda}
subjects: [{kind: ServiceAccount, name: omni-compass, namespace: omni-compass}]
