# SPDX-License-Identifier: LicenseRef-OmniCompass-Evaluation-1.0
# Copyright (c) 2026 The Omni-Compass LLC. Evaluation and simulation use only; any other use requires a signed, paid
# Omni-Compass Enterprise License. See LICENSE.
# Additional write access for --mode target: patch and annotate HPAs only. Apply only after an observe period.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: {name: omni-compass-target}
rules:
  - apiGroups: [autoscaling]
    resources: [horizontalpodautoscalers]
    verbs: [patch, update]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: {name: omni-compass-target}
roleRef: {apiGroup: rbac.authorization.k8s.io, kind: ClusterRole, name: omni-compass-target}
subjects: [{kind: ServiceAccount, name: omni-compass, namespace: omni-compass}]
