# SPDX-License-Identifier: LicenseRef-OmniCompass-Evaluation-1.0
# Copyright (c) 2026 The Omni-Compass LLC. All rights reserved.
# Evaluation and simulation use only; any commercialization, monetization or other use requires a signed, paid
# Omni-Compass Enterprise License. See LICENSE, NOTICE and DISCLOSURES.md.
# All patents, copyrights and trademarks filed in the USA. www.omni-compass.com
# The add-on native, profile "both" (ADDONS_PROFILE=both, the default): KEDA owns php-apache's autoscaler and scales on two
# signals at once, the HPA's own CPU target (50% of the pods' request, as demo.yaml's HPA) and the HTTP add-on's live
# requests in flight (deploy/kind/addons/keda-route.yaml). KEDA builds the HPA under the same name, php-apache, so every
# reading of the cluster is the same as in every other set; the autoscaler takes whichever signal asks for more pods.
# Replica range 1 to 10, as demo.yaml (MAX_REPLICAS is replaced by scripts/kind_addons.sh with HPA_MAX or 10).
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata: {name: php-apache, namespace: default}
spec:
  scaleTargetRef: {apiVersion: apps/v1, kind: Deployment, name: php-apache}
  minReplicaCount: 1
  maxReplicaCount: MAX_REPLICAS
  advanced:
    horizontalPodAutoscalerConfig: {name: php-apache}
  triggers:
    - type: cpu
      metricType: Utilization
      metadata: {value: "50"}
    - type: external-push
      metadata:
        interceptorRoute: php-apache
        scalerAddress: keda-add-ons-http-external-scaler.keda:9090
