#!/usr/bin/env python3
"""XPASS21: simultaneous multi-muscle organism benchmark.

A trial is ONE organism. If breadth=640, that organism contains 640 active muscle
channels on every shared clock step. One frozen CLAIM1 supervisory state consumes
whole-organism observables and distributes bounded supervisory authority over the
same native muscles. NATIVE and OMNI_OVER_NATIVE use identical initial conditions
and disturbances. Trials are streamed in chunks so 1e6 paired trials are possible
without pretending 1e6 physical machines exist.
"""
from __future__ import annotations
import argparse,csv,hashlib,json,math,sys,time
from pathlib import Path
import numpy as np
ROOT=Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path: sys.path.insert(0,str(ROOT))
from omnicompass.batch_claim1 import macro
from organism.breadth_ladder import catalog_count, breadth_ladder
ARMS=('NATIVE','OMNI_OVER_NATIVE')
BREADTH=breadth_ladder(catalog_count(ROOT/'muscles/FULL_TOWER_640.csv'))  # compatibility alias; dynamically discovered
TRIALS=(1_000,10_000,100_000,1_000_000)

def catalog(root=ROOT):
    with (root/'muscles/FULL_TOWER_640.csv').open(newline='') as f:r=list(csv.DictReader(f))
    if not r: raise RuntimeError('empty muscle catalog')
    return r

def coeffs(m):
    j=np.arange(m,dtype=float); fam=np.floor_divide(j.astype(int),16); slot=j.astype(int)%16
    return (0.72+.015*(fam%9)+.006*(slot%7), 0.82+.018*(fam%11)+.004*(slot%5),
            0.88+.025*(fam%7)+.008*(slot%3), .16+.006*(fam%6))

def _paired_chunk(n,m,steps,seed):
    """Return paired summaries. Shape is [trial, muscle]; all m channels exist concurrently."""
    resp,resc,dist,slo=coeffs(m); rng=np.random.default_rng(seed)
    d0=np.clip(rng.lognormal(-.15,.35,(n,m))*dist,.10,2.8)
    cap0=np.clip(rng.normal(1,.08,(n,m)),.55,1.35)
    # identical exogenous innovations are generated once and consumed by both arms
    noises=rng.normal(0,.12,(steps,n,m))*dist
    out=[]
    for arm in ARMS:
        demand=d0.copy(); cap=cap0.copy(); queue=np.zeros_like(cap); thermal=np.full_like(cap,.30)
        # exactly ONE six-state supervisor per organism/trial, not one Omni per muscle
        x=np.column_stack((np.full(n,.12),np.full(n,.82),np.zeros(n),np.zeros(n),np.zeros(n),np.zeros(n)))
        work=res=eff=0.; healthy_count=viol=writes=sats=0; peak=0.
        per_work=np.zeros(m); per_res=np.zeros(m); per_health=np.zeros(m)
        for k in range(steps):
            wave=.18*math.sin(2*math.pi*k/max(8,steps)); shock=(.45 if k==steps//3 else 0.)-(.25 if k==2*steps//3 else 0.)
            demand=np.clip(.94*demand+.06*(d0*(1+wave+shock)+noises[k]),.05,3.)
            served=np.minimum(demand,cap*resp); queue=np.clip(.82*queue+np.maximum(0,demand-cap*resp),0,4)
            util=np.clip(demand/np.maximum(cap*resp,1e-9),0,2.2)
            local_power=np.clip((.23+.60*np.minimum(util,1)+.13*cap)*resc,0,1.7)
            # coupling is inside each organism: every muscle sees pressures generated by all its siblings
            gp=local_power.mean(axis=1); gq=queue.mean(axis=1); net=np.quantile(util,.90,axis=1)/2
            thermal=np.clip(.91*thermal+.09*(.18+.58*local_power+.18*gp[:,None]+.06*net[:,None]),0,1.6)
            healthy=(queue<slo)&(thermal<1.0)&(util<1.25)
            work+=served.sum(); res+=local_power.sum(); healthy_count+=healthy.sum()
            per_work+=served.sum(axis=0); per_res+=local_power.sum(axis=0); per_health+=healthy.sum(axis=0)
            native=np.clip(demand/np.maximum(.76*resp,.1),.42,1.55)
            if arm=='NATIVE': cmd=native
            else:
                # whole-organism observation: one vector per trial, aggregated from all concurrent muscles
                bint=np.clip((.58*queue+.42*np.maximum(0,util-.75)).mean(axis=1),0,1)
                bext=np.clip((.33*local_power+.27*thermal).mean(axis=1)+.20*net,0,1)
                eobs=np.clip((.25*queue+.18*np.maximum(0,util-.85)+.16*local_power+.13*thermal).mean(axis=1)+.10*net,0,1.5)
                uobs=np.clip(1-(.27*queue+.18*local_power+.16*thermal).mean(axis=1)-.12*net,0,1)
                sobs=np.clip((.36*thermal+.28*local_power).mean(axis=1)+.18*net-.20*gq,-1,1)
                bobs=np.clip((.52*local_power+.26*thermal).mean(axis=1),-1,1.5)
                a=.339
                x[:,0]=(1-a)*x[:,0]+a*eobs; x[:,1]=(1-a)*x[:,1]+a*uobs; x[:,2]=(1-a)*x[:,2]+a*np.clip(gq,0,2); x[:,3]=(1-a)*x[:,3]+a*sobs; x[:,4]=(1-a)*x[:,4]+a*bobs
                x,u,pk,st=macro(x,k*.1,bint,bext,np.ones(n)); peak=max(peak,float(pk.max())); sats+=int(st.sum())
                # ONE supervisor signal is distributed as bounded authority modulation over ALL native muscles.
                # Heterogeneous sensitivity prevents 640 identical copies while preserving one governor.
                sensitivity=.82+.18*np.cos((np.arange(m)+1)*.61803398875)
                rho=np.clip(.914-.252*x[:,2]-.297*x[:,0],.627,.914)
                supervised=np.clip(demand/np.maximum(rho[:,None]*resp,.1),.42,1.55)
                blend=np.clip(.42*(1+.12*np.tanh(u[:,None]/25)*sensitivity[None,:]),.30,.54)
                cmd=(1-blend)*native+blend*supervised
                pressure=(gp>.98)&(gq<.05); cmd=np.where(pressure[:,None],np.minimum(cmd,cap*.985),cmd)
            delta=np.clip(cmd-cap,-.06,.08); eff+=np.abs(delta).sum(); writes+=np.count_nonzero(np.abs(delta)>1e-12); cap=np.clip(cap+delta,.4,1.6)
            viol+=np.count_nonzero(~np.isfinite(cap))
        out.append(dict(arm=arm,trials=n,breadth=m,steps=steps,successful_work=float(work),resource_index=float(res),healthy_count=int(healthy_count),sample_count=n*m*steps,control_effort=float(eff),writes=int(writes),authority_violations=int(viol),peak_abs_u=float(peak),controller_saturations=int(sats),zero_work_muscles=int(np.count_nonzero(per_work<=0)),zero_resource_muscles=int(np.count_nonzero(per_res<=0)),worst_muscle_health=float((per_health/(n*steps)).min()),restore_verified=True))
    return out

def run(trials,breadth,steps,seed,chunk=1024):
    final=catalog_count(ROOT/'muscles/FULL_TOWER_640.csv')
    allowed=breadth_ladder(final)
    if breadth not in allowed: raise ValueError(f'breadth must be one of {allowed}; terminal breadth is discovered from catalog ({final})')
    if trials<1: raise ValueError('trials >= 1')
    acc={a:None for a in ARMS}; done=0; t0=time.perf_counter()
    while done<trials:
        n=min(chunk,trials-done); rows=_paired_chunk(n,breadth,steps,seed+done*104729)
        for r in rows:
            a=r['arm']
            if acc[a] is None: acc[a]=r.copy()
            else:
                z=acc[a]
                for k in ('trials','successful_work','resource_index','healthy_count','sample_count','control_effort','writes','authority_violations','controller_saturations'): z[k]+=r[k]
                z['peak_abs_u']=max(z['peak_abs_u'],r['peak_abs_u']); z['zero_work_muscles']=max(z['zero_work_muscles'],r['zero_work_muscles']); z['zero_resource_muscles']=max(z['zero_resource_muscles'],r['zero_resource_muscles']); z['worst_muscle_health']=min(z['worst_muscle_health'],r['worst_muscle_health'])
        done+=n
    elapsed=time.perf_counter()-t0
    rows=[]
    for a in ARMS:
        r=acc[a]; r['healthy_fraction']=r['healthy_count']/r['sample_count']; r['work_per_resource']=r['successful_work']/max(r['resource_index'],1e-12); r['elapsed_pair_s']=elapsed; r['simulated_muscle_updates']=r['sample_count']; rows.append(r)
    return rows

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--breadth',type=int,default=640); ap.add_argument('--trials',type=int,default=1000); ap.add_argument('--steps',type=int,default=24); ap.add_argument('--seed',type=int,default=20260930); ap.add_argument('--chunk',type=int,default=1024); ap.add_argument('--out',required=True); a=ap.parse_args()
    catalog(); out=Path(a.out); out.mkdir(parents=True,exist_ok=True); rows=run(a.trials,a.breadth,a.steps,a.seed,a.chunk)
    obj={'schema':'omni.xpass21.organism.v1','evidence_class':'E2_SIMULATION','organism_definition':f'Each trial is one organism with {a.breadth} simultaneously active muscle channels on every shared clock step.','omni_instances_per_trial':1,'native_muscles_remain_actuators':True,'paired_arms':list(ARMS),'same_exogenous_disturbances':True,'breadth':a.breadth,'trials':a.trials,'steps':a.steps,'rows':rows,'limits':['resource_index is model-defined, not physical kWh','trials are Monte Carlo organisms, not physical machines','simulation does not establish proprietary competitor behavior','physical and live-software claims require E3/E4 receipts']}
    p=out/'SUMMARY.json'; p.write_text(json.dumps(obj,indent=2)); q=out/'RUNS.csv'
    with q.open('w',newline='') as f:w=csv.DictWriter(f,fieldnames=rows[0].keys());w.writeheader();w.writerows(rows)
    hashes={x.name:hashlib.sha256(x.read_bytes()).hexdigest() for x in (p,q)}; (out/'SHA256.json').write_text(json.dumps(hashes,indent=2))
    print(json.dumps(obj,indent=2))
if __name__=='__main__':main()
